[package]
name = "parsec-executor"
version = "0.1.0"
edition = "2021"

[dependencies]
parsec-core = { path = "../core" }
tokio = { version = "1.0", features = ["full"] }
chrono = { version = "0.4", features = ["serde"] }
anyhow = "1.0"
